### ISSUE TITLE
Add color for each point

### ISSUE THREAD

**Issue by dridk** [octree-gva/Zeitline#12]
Is it possible to add different color for each point ? 

```
    {date: new Date('31 Jan 2017'), color: 'red'},
    {date: new Date('10 May 2017'), color: 'blue'},
    {date: new Date('11 May 2017'), color: 'yellow'},
```

**Comment by BafS** [comment]
I merged a PR to expose the labels in the group, like that you can use selectors to change the color.

For example

```js
    {date: new Date('31 Jan 2017'), label: 'red'},
    {date: new Date('10 May 2017'), label: 'blue'},
    {date: new Date('11 May 2017'), label: 'yellow'},
```

with this CSS:
```css
g[data-label-start="yellow"] rect {
    fill: yellow;
}
g[data-label-start="red"] rect {
    fill: red;
}
g[data-label-start="blue"] rect {
    fill: blue;
}
```

It's a bit more complicated with clusters, there is the `data-label-start` and `data-label-end` to represent the first and last label of the cluster.
